import {build} from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
const app=process.argv[2];
if(!app)throw Error('Pass the original App checkout explicitly; never generate golden results from the port');
const root=fileURLToPath(new URL('..',import.meta.url));
const out=path.join(root,'dist/source-app-golden.mjs');
const stubs={
  '@env':'export const AGENT_SIMULATION_API_URL="",LLM_API_BASE_URL="",LLM_API_KEY="",LLM_MODEL="",ZHIPU_API_KEY="",ZHIPU_MODEL="";',
  'react-native':'export const Platform={OS:"ios"};',
  'storage':'export const storage={getItem:async()=>null,setItem:async()=>{},removeItem:async()=>{}};',
  'aapsRelayConfig':'export const loadAapsRelayClient=async()=>null;',
  'aapsToolRuntime':'export const createAapsAgentToolProvider=()=>null;',
  'dataSourceManager':'export const dataSourceManager={getCurrentAdapter:()=>null};',
};
await build({stdin:{contents:`export {answerAgentQuery} from './src/agent/agentService';export {DEFAULT_EXPERT_RULES} from './src/agent/expertRules';export {createSyntheticSimulationInput,runIntegratedSimulation} from './src/agent/simulationClient';export {runLoopInsightScenario} from './src/agent/loopinsightKernel/scenarioRunner';`,resolveDir:app,loader:'ts'},outfile:out,bundle:true,platform:'node',format:'esm',packages:'external',plugins:[{name:'mobile-boundaries-only',setup(b){b.onResolve({filter:/.*/},a=>{const key=a.path in stubs?a.path:path.basename(a.path);if(key in stubs)return {path:key,namespace:'stub'};});b.onLoad({filter:/.*/,namespace:'stub'},a=>({contents:stubs[a.path],loader:'js'}));}}]});
const source=await import(pathToFileURL(out));
const RealDate=Date;
globalThis.Date=class extends RealDate{constructor(...args){super(...(args.length?args:['2026-09-01T04:00:00.000Z']));}static now(){return new RealDate('2026-09-01T04:00:00.000Z').getTime();}};
const snapshot=source.createSyntheticSimulationInput();
const answers=[];
const provider={invoke:async()=>({status:'succeeded',summary:'Read Nightscout data; relay history is not patient treatment history',data:snapshot})};
for(const [route,query] of [['rag_qa','什么是IOB'],['daily_report','生成日报'],['weekly_report','生成周报'],['current_state','检查当前状态']]){
  const answer=await source.answerAgentQuery({...snapshot,query,forcedRoute:route,now:new Date(),rules:source.DEFAULT_EXPERT_RULES,aapsProvider:provider});
  answers.push({route,query,answer});
}
// Evidence selection is also loaded from the original checkout, not regenerated by the port.
await build({stdin:{contents:`export {retrieveDecisionEvidence} from './src/agent/decisionEvidence';export {buildPatientDecisionState} from './src/agent/patientDecisionState';`,resolveDir:app,loader:'ts'},outfile:path.join(root,'dist/source-evidence.mjs'),bundle:true,platform:'node',format:'esm',packages:'external'});
const evidenceSource=await import(pathToFileURL(path.join(root,'dist/source-evidence.mjs')));
const simulationInput={...snapshot,approvedHypoCarbsG:null,evidence:evidenceSource.retrieveDecisionEvidence(evidenceSource.buildPatientDecisionState(snapshot))};
const simulation=await source.runIntegratedSimulation(simulationInput);
const scenarios=[];
for(const hours of [2,24]){
  const input={start:'2026-09-01T00:00:00.000Z',end:new RealDate(RealDate.parse('2026-09-01T00:00:00.000Z')+hours*3600000).toISOString(),dtMinutes:5,seed:42,basalRateUPerHour:0.8,meals:[{start:'2026-09-01T00:30:00.000Z',duration:15,carbs:30}],exercise:[{start:'2026-09-01T01:00:00.000Z',duration:30,intensity:25}]};
  scenarios.push({input,points:source.runLoopInsightScenario(input)});
}
globalThis.Date=RealDate;
fs.mkdirSync(path.join(root,'tests/fixtures'),{recursive:true});
fs.writeFileSync(path.join(root,'tests/fixtures/source-app-golden.json'),JSON.stringify({provenance:'Executed original App source; only mobile storage/config/data provider stubbed. Synthetic data only.',now:'2026-09-01T04:00:00.000Z',snapshot,simulationInput,answers,simulation,scenarios},null,2)+'\n');
console.log('Wrote original-App golden: 4 workflow routes, 2-plan simulation, 2h and 24h meal/exercise scenarios');
